//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace uneidel.Prototype.ServicePortal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Logging> Loggings
        {
            get
            {
                if ((_Loggings == null))
                {
                    _Loggings = base.CreateObjectSet<Logging>("Loggings");
                }
                return _Loggings;
            }
        }
        private ObjectSet<Logging> _Loggings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderEntity> OrderEntities
        {
            get
            {
                if ((_OrderEntities == null))
                {
                    _OrderEntities = base.CreateObjectSet<OrderEntity>("OrderEntities");
                }
                return _OrderEntities;
            }
        }
        private ObjectSet<OrderEntity> _OrderEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SimpleAccessModel> SimpleAccessModels
        {
            get
            {
                if ((_SimpleAccessModels == null))
                {
                    _SimpleAccessModels = base.CreateObjectSet<SimpleAccessModel>("SimpleAccessModels");
                }
                return _SimpleAccessModels;
            }
        }
        private ObjectSet<SimpleAccessModel> _SimpleAccessModels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuotaEntity> QuotaEntities
        {
            get
            {
                if ((_QuotaEntities == null))
                {
                    _QuotaEntities = base.CreateObjectSet<QuotaEntity>("QuotaEntities");
                }
                return _QuotaEntities;
            }
        }
        private ObjectSet<QuotaEntity> _QuotaEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SCEntity> SCEntities
        {
            get
            {
                if ((_SCEntities == null))
                {
                    _SCEntities = base.CreateObjectSet<SCEntity>("SCEntities");
                }
                return _SCEntities;
            }
        }
        private ObjectSet<SCEntity> _SCEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SampleData> SampleDatas
        {
            get
            {
                if ((_SampleDatas == null))
                {
                    _SampleDatas = base.CreateObjectSet<SampleData>("SampleDatas");
                }
                return _SampleDatas;
            }
        }
        private ObjectSet<SampleData> _SampleDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BehoerdenEntity> BehoerdenEntities
        {
            get
            {
                if ((_BehoerdenEntities == null))
                {
                    _BehoerdenEntities = base.CreateObjectSet<BehoerdenEntity>("BehoerdenEntities");
                }
                return _BehoerdenEntities;
            }
        }
        private ObjectSet<BehoerdenEntity> _BehoerdenEntities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Loggings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoggings(Logging logging)
        {
            base.AddObject("Loggings", logging);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderEntities(OrderEntity orderEntity)
        {
            base.AddObject("OrderEntities", orderEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SimpleAccessModels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSimpleAccessModels(SimpleAccessModel simpleAccessModel)
        {
            base.AddObject("SimpleAccessModels", simpleAccessModel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuotaEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuotaEntities(QuotaEntity quotaEntity)
        {
            base.AddObject("QuotaEntities", quotaEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SCEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSCEntities(SCEntity sCEntity)
        {
            base.AddObject("SCEntities", sCEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SampleDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSampleDatas(SampleData sampleData)
        {
            base.AddObject("SampleDatas", sampleData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BehoerdenEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBehoerdenEntities(BehoerdenEntity behoerdenEntity)
        {
            base.AddObject("BehoerdenEntities", behoerdenEntity);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BA.POC.ServicePortalModel", Name="BehoerdenEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BehoerdenEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BehoerdenEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="behoerdenName">Initial value of the BehoerdenName property.</param>
        public static BehoerdenEntity CreateBehoerdenEntity(global::System.Int32 id, global::System.String behoerdenName)
        {
            BehoerdenEntity behoerdenEntity = new BehoerdenEntity();
            behoerdenEntity.Id = id;
            behoerdenEntity.BehoerdenName = behoerdenName;
            return behoerdenEntity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BehoerdenName
        {
            get
            {
                return _BehoerdenName;
            }
            set
            {
                OnBehoerdenNameChanging(value);
                ReportPropertyChanging("BehoerdenName");
                _BehoerdenName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BehoerdenName");
                OnBehoerdenNameChanged();
            }
        }
        private global::System.String _BehoerdenName;
        partial void OnBehoerdenNameChanging(global::System.String value);
        partial void OnBehoerdenNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BA.POC.ServicePortalModel", Name="Logging")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Logging : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Logging object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        /// <param name="action">Initial value of the Action property.</param>
        /// <param name="user">Initial value of the User property.</param>
        public static Logging CreateLogging(global::System.Guid id, global::System.DateTime dateTime, global::System.String action, global::System.String user)
        {
            Logging logging = new Logging();
            logging.Id = id;
            logging.DateTime = dateTime;
            logging.Action = action;
            logging.User = user;
            return logging;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BA.POC.ServicePortalModel", Name="OrderEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="approval">Initial value of the Approval property.</param>
        public static OrderEntity CreateOrderEntity(global::System.Guid id, global::System.String type, global::System.String status, global::System.DateTime createDate, global::System.String user, global::System.String approval)
        {
            OrderEntity orderEntity = new OrderEntity();
            orderEntity.Id = id;
            orderEntity.Type = type;
            orderEntity.Status = status;
            orderEntity.CreateDate = createDate;
            orderEntity.User = user;
            orderEntity.Approval = approval;
            return orderEntity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Approval
        {
            get
            {
                return _Approval;
            }
            set
            {
                OnApprovalChanging(value);
                ReportPropertyChanging("Approval");
                _Approval = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Approval");
                OnApprovalChanged();
            }
        }
        private global::System.String _Approval;
        partial void OnApprovalChanging(global::System.String value);
        partial void OnApprovalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BA.POC.ServicePortalModel", Name="QuotaEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuotaEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuotaEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="quota">Initial value of the Quota property.</param>
        public static QuotaEntity CreateQuotaEntity(global::System.Guid id, global::System.String name, global::System.String quota)
        {
            QuotaEntity quotaEntity = new QuotaEntity();
            quotaEntity.Id = id;
            quotaEntity.Name = name;
            quotaEntity.Quota = quota;
            return quotaEntity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Quota
        {
            get
            {
                return _Quota;
            }
            set
            {
                OnQuotaChanging(value);
                ReportPropertyChanging("Quota");
                _Quota = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Quota");
                OnQuotaChanged();
            }
        }
        private global::System.String _Quota;
        partial void OnQuotaChanging(global::System.String value);
        partial void OnQuotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Guid> _Order;
        partial void OnOrderChanging(Nullable<global::System.Guid> value);
        partial void OnOrderChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BA.POC.ServicePortalModel", Name="SampleData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SampleData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SampleData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        public static SampleData CreateSampleData(global::System.Guid id, global::System.String dateTime, global::System.String amount)
        {
            SampleData sampleData = new SampleData();
            sampleData.Id = id;
            sampleData.DateTime = dateTime;
            sampleData.Amount = amount;
            return sampleData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.String _DateTime;
        partial void OnDateTimeChanging(global::System.String value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.String _Amount;
        partial void OnAmountChanging(global::System.String value);
        partial void OnAmountChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BA.POC.ServicePortalModel", Name="SCEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SCEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SCEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="template">Initial value of the Template property.</param>
        /// <param name="quota">Initial value of the Quota property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        /// <param name="behoerdenId">Initial value of the BehoerdenId property.</param>
        /// <param name="sCOwner">Initial value of the SCOwner property.</param>
        public static SCEntity CreateSCEntity(global::System.Guid id, global::System.String name, global::System.String description, global::System.String template, global::System.String quota, global::System.Guid order, global::System.Int32 behoerdenId, global::System.String sCOwner)
        {
            SCEntity sCEntity = new SCEntity();
            sCEntity.Id = id;
            sCEntity.Name = name;
            sCEntity.Description = description;
            sCEntity.Template = template;
            sCEntity.Quota = quota;
            sCEntity.Order = order;
            sCEntity.BehoerdenId = behoerdenId;
            sCEntity.SCOwner = sCOwner;
            return sCEntity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Template
        {
            get
            {
                return _Template;
            }
            set
            {
                OnTemplateChanging(value);
                ReportPropertyChanging("Template");
                _Template = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Template");
                OnTemplateChanged();
            }
        }
        private global::System.String _Template;
        partial void OnTemplateChanging(global::System.String value);
        partial void OnTemplateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Quota
        {
            get
            {
                return _Quota;
            }
            set
            {
                OnQuotaChanging(value);
                ReportPropertyChanging("Quota");
                _Quota = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Quota");
                OnQuotaChanged();
            }
        }
        private global::System.String _Quota;
        partial void OnQuotaChanging(global::System.String value);
        partial void OnQuotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Guid _Order;
        partial void OnOrderChanging(global::System.Guid value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BehoerdenId
        {
            get
            {
                return _BehoerdenId;
            }
            set
            {
                OnBehoerdenIdChanging(value);
                ReportPropertyChanging("BehoerdenId");
                _BehoerdenId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BehoerdenId");
                OnBehoerdenIdChanged();
            }
        }
        private global::System.Int32 _BehoerdenId;
        partial void OnBehoerdenIdChanging(global::System.Int32 value);
        partial void OnBehoerdenIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SCOwner
        {
            get
            {
                return _SCOwner;
            }
            set
            {
                OnSCOwnerChanging(value);
                ReportPropertyChanging("SCOwner");
                _SCOwner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SCOwner");
                OnSCOwnerChanged();
            }
        }
        private global::System.String _SCOwner;
        partial void OnSCOwnerChanging(global::System.String value);
        partial void OnSCOwnerChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BA.POC.ServicePortalModel", Name="SimpleAccessModel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SimpleAccessModel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SimpleAccessModel object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        public static SimpleAccessModel CreateSimpleAccessModel(global::System.Guid id, global::System.String userName, global::System.String password, global::System.String role)
        {
            SimpleAccessModel simpleAccessModel = new SimpleAccessModel();
            simpleAccessModel.Id = id;
            simpleAccessModel.UserName = userName;
            simpleAccessModel.Password = password;
            simpleAccessModel.Role = role;
            return simpleAccessModel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();

        #endregion

    
    }

    #endregion

    
}
